### ISSUE TITLE
br_table jump arguments

### ISSUE THREAD

**Issue by denismerigoux** [stoklund/cretonne#101]
@sunfishcode and I ran into a problem when translating wasm into Cretonne IL. In wasm, the `br_table` instruction actually pops some return values from the stack and passes them to the block it is jumping to. However in Cretonne IL, contrary to the other branch instructions, `br_table` does not support jump arguments. This means that the `Ebb` that are in the jump table used by `br_table` must not have arguments. We don't know if this is done on purpose or not.

Here is the alternative space for solving this inconsistency:

- either add an jump arguments field for the Cretonne IL `br_table` and require that all `Ebb`s inside a jump table have the same arguments count and types ;

- either leave `br_table` as is but then it would mean that we would need to use `stack_store` and `stack_load` when we want to pass arguments to an `Ebb` that is target of a `br_table` instruction.

**Comment by stoklund** [comment]
If a `br_table` can take arguments, it becomes very difficult to modify EBB arguments anywhere. If a predecessor is a `br_table`, you then have to find all of its successors and modify their arguments too, transitively.

You also have the option of splitting critical edges such that each target of a `br_table` only has a single predecessor.

**Comment by stoklund** [comment]
This is one place where the "EBB argument" notation differs from "phi function" notation. With phi functions, each successor of a `br_table` can take an independent set of arguments since it has its own phi functions. This is nice and practical for building the IL, but it leads to horrible code generation. You might as well use `stack_store` since everything is going to spill anyway.

The median solution which you proposed here is to have all successors take identical arguments. That doesn't mess up code generation the same way, but it is a difficult invariant to maintain. Just computing the set of EBBs that must have identical argument signatures is tricky. See [LLVM's CFG edge bundle analysis](http://www.llvm.org/docs/doxygen/html/classllvm_1_1EdgeBundles.html).

I would prefer to keep `br_table` without arguments which leaves you two possibilities when generating code:

1. Pass values through memory with `stack_store` and `stack_load`, or
2. Make sure that `br_table` successors never have multiple predecessors by splitting edges.

**Comment by denismerigoux** [comment]
Thanks for the explanation, now I understand the choice. The two solutions are indeed quite equivalent but I think I'll go with edge splitting for my translation.

**Comment by denismerigoux** [comment]
Problem solved in #97 with on demand critical edge splitting.

**Comment by vitiral** [comment]
Sorry, I'm trying to understand cranelift IR. I think I'm missing some of the required background here (graph theory?). [br_table](https://cranelift.readthedocs.io/en/latest/ir.html#inst-br_table) is confusing me, and the discussion in this issue helped clear things up a bit, but I still don't know what "critical edge splitting" is.

https://en.wikipedia.org/wiki/Control_flow_graph has this to say

> A critical edge is an edge which is neither the only edge leaving its source block, nor the only edge entering its destination block. These edges must be split: a new block must be created in the middle of the edge, in order to insert computations on the edge without affecting any other edges.

Okay... so an edge is the line going from one node to another... but then I'm pretty lost.

**Comment by sunfishcode** [comment]
Yes, that Wikipedia article is right. To illustrate, a critical edge is an edge in the CFG where its source has multiple successors (eg. a block ending in a conditional branch to multiple possible destinations) and its destination has multiple predecessors, such as the red edge in this diagram:

![critical edge](https://user-images.githubusercontent.com/4503403/52359375-a3e28f00-29ee-11e9-83be-025f9aeb4dab.png)

Critical edge splitting is the process of inserting an extra node along that edge (eg. an extra unconditional branch), which for the above diagram looks like this:

![split](https://user-images.githubusercontent.com/4503403/52359541-f6bc4680-29ee-11e9-9253-c66942a74526.png)

**Comment by denismerigoux** [comment]
So this critical edge splitting has to to with SSA construction in the IR. Indeed, when you have a situation like this: 
![untitled diagram](https://user-images.githubusercontent.com/1766128/52359918-2133f100-2a3b-11e9-9eaf-501ffcfe4d74.png)

The problem is that you cannot put a jump argument in the edge with "Arg: ?" because `br_table` does not support them. To fix that you take the edge with "Arg: ?" and split it in the way @sunfishcode presented just above.

I hope it helped you understand what was happening :)

**Comment by vitiral** [comment]
I now understand what a critical edge is... I'm still extremely confused how you "use" this fact to "workaround... pass[ing] arguments to the targeted blocks" [`[1]`][1].

All values in the rest of the guide are either from EBB arguments or previous SSA values. Once you "jump" into either the default `EBB` or the `JT[x]`... where does it get it's values?

I'm sure I have some fundamental misunderstanding of how this all works, since I actually don't understand how you could use `stack_store` or `stack_load` _at all_ without some reference to which index you are loading/storing. Sorry if these are dumb questions.

[1]: https://cranelift.readthedocs.io/en/latest/ir.html#inst-br_table

**Comment by sunfishcode** [comment]
These are good questions, and very welcome!

The main way that critical edge splitting helps is instead of adding arguments to `br_table` itself, you can have `br_table`'s destinations be little blocks that each just contain a single direct branch to a real destination (thus splitting the edges), and then you can add arguments to those direct branches.

Another thing which may be helpful is cranelift-frontend's support for SSA building: see [here](https://docs.rs/cranelift-frontend/0.28.0/cranelift_frontend/#mutable-variables-and-cranelift-ir-values) for an overview. This is relevant because if you can fit what you're doing into the framework of mutable variables, then the library can take care of adding block parameters and branch arguements, including splitting critical edges, fully automatically.

Concerning `stack_store` and `stack_load`, the indices for these are declared in the function preamble. See [here](https://cranelift.readthedocs.io/en/latest/ir.html#overall-structure) for an example that shows a stack slot declaration. These stack slots are scoped to the entire function body, so they don't depend on block parameters to be visible.

**Comment by vitiral** [comment]
Okay, I think I'm closer to understanding. I think there is one more bit of context I am still missing though.

I had the expectation (from my limited understanding of wasm) that `br_table` would be the primary command for utilizing external/dynamic libraries. It is slightly difficult to see how this is done, at least directly.

I searched for `br_table` through the cranelift source and came across this in `cranelift_wasm/src/code_translator.rs`

```rust
        /**************************** Branch instructions *********************************
         * The branch instructions all have as arguments a target nesting level, which
         * corresponds to how many control stack frames do we have to pop to get the
         * destination `Ebb`.
         *
         * Once the destination `Ebb` is found, we sometimes have to declare a certain depth
         * of the stack unreachable, because some branch instructions are terminator.
         *
         * The `br_table` case is much more complicated because Cranelift's `br_table` instruction
         * does not support jump arguments like all the other branch instructions. That is why, in
         * the case where we would use jump arguments for every other branch instructions, we
         * need to split the critical edges leaving the `br_tables` by creating one `Ebb` per
         * table destination; the `br_table` will point to these newly created `Ebbs` and these
         * `Ebb`s contain only a jump instruction pointing to the final destination, this time with
         * jump arguments.
         *
         * This system is also implemented in Cranelift's SSA construction algorithm, because
         * `use_var` located in a destination `Ebb` of a `br_table` might trigger the addition
         * of jump arguments in each predecessor branch instruction, one of which might be a
         * `br_table`.
         ***********************************************************************************/
        ...
        Operator::BrTable { table } => {
        ...
          if jump_args_count == 0 {
                // No jump arguments
            ...
            } else {
                // Here we have jump arguments, but Cranelift's br_table doesn't support them
                // We then proceed to split the edges going out of the br_table
            ...
        }
```

So it looks like:

* cranelift doesn't support `br_table` with arguments natively
* every time a `br_table` operation with arguments is needed, cranelift has to extract them from the source's table-call into a specialized EBB _within the jump table for just that localized call_. It's still not completely clear to me how it "injects" the values, I think it has to do with inserting the arguments via the _stack_ with something like `state.peekn(return_count)` and `state.popn(return_count)`.

**Comment by vitiral** [comment]
One thing that might help me understand is a `.clif` example of how to call an external function with arguments. Looking through the tests I'm not seeing any real examples.

**Comment by sunfishcode** [comment]
`br_table` is for jump tables with destinations within the current function only -- think of a `match` in Rust or a `switch` in C. If you want to call a function in a dynamic library, that will typically use `call_indirect`. `br_table` and `call_indirect` may lower down to some of the same instructions in hardware, but Cranelift thinks about the two very differently.

If you're looking at `state.peekn` and `state.popn` calls, that's in the WebAssembly translator, and in that context it's important to keep in mind that "the stack" refers to the WebAssembly operand stack, which is an abstraction in the WebAssembly binary format. WebAssembly operand stack slots are translated into virtual register uses and defs in Cranelift IR, rather than `stack_load/store` operations.

Does that clarify things? I'm unclear on exactly what kind of example you're looking for, but hopefully the above clears up some of the terminology in use.

**Comment by vitiral** [comment]
Wow, that is incredibly useful context!
